/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaDeReservas.java
 *
 * Created on 12/07/2010, 21:26:19
 */

package br.com.apresentacao.telas;

import br.com.apresentacao.controladoras.IInteracaoCliente;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Netbeans
 * @version 0.2
 */
public class TelaDeReservas extends javax.swing.JFrame {

    /**Referencia para esta classe.*/
    private static TelaDeReservas referencia = null;
    /** Controladora de Interacao */
    private IInteracaoCliente cntrInteracao;

    /** Creates new form TelaDeReservas. */
    public TelaDeReservas() {
        super("Reservas");
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reservas Cadastradas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Reserva 1", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Reserva 2", jScrollPane2);

        jButton3.setText("Nova Reserva");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar Reserva");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cntrInteracao.efetuarReserva();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cntrInteracao.cancelarReserva(
               JOptionPane.showInputDialog("Insira o código da reserva:"));
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public void setControladora(IInteracaoCliente cntrInteracao) {
        this.cntrInteracao = cntrInteracao;
    }

    public void setCodReserva1(String reserva) {
        if (reserva != null) {
            jTabbedPane1.setTitleAt(0, reserva);
        } else {
            jTabbedPane1.setTitleAt(0, "");
            jTabbedPane1.setEnabledAt(0, false);
        }
    }

    public void setCodReserva2(String reserva) {
        if (reserva != null) {
            jTabbedPane1.setTitleAt(1, reserva);
        } else {
            jTabbedPane1.setTitleAt(1, "");
            jTabbedPane1.setEnabledAt(1, false);
        }
    }

    public void setTableDisabled() {
        jTable1.setEnabled(false);
        jTable2.setEnabled(false);
    }

    public void addTable1(String numero, String de, String codDe, String para,
            String codPara, String dataSaida, String dataChegada,
            String horaSaida, String horaChegada) {
        DefaultTableModel model=((DefaultTableModel)jTable1.getModel());
        String []string = new String[] {numero, de, codDe, para, codPara,
        dataSaida, dataChegada, horaSaida, horaChegada};
        model.addRow(string);
    }

    public void addTable2(String numero, String de, String codDe, String para,
            String codPara, String dataSaida, String dataChegada,
            String horaSaida, String horaChegada) {
        DefaultTableModel model=((DefaultTableModel)jTable2.getModel());
        String []string = new String[] {numero, de, codDe, para, codPara,
        dataSaida, dataChegada, horaSaida, horaChegada};
        model.addRow(string);
    }

    private void setModel() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código do Voo", "De", "Cod. Aeroporto.", "Para",
                "Cod. Aeroporto", "Data Saída", "Data Chegada", "Hora Saída",
                "Hora Chegada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código do Voo", "De", "Cod. Aeroporto.", "Para",
                "Cod. Aeroporto", "Data Saída", "Data Chegada", "Hora Saída",
                "Hora Chegada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }
}
